### ISSUE TITLE
Making a great SharePoint Default List/Library View

### ISSUE THREAD

**Issue by PatD** [MicrosoftDocs/microsoft-365-community#186]
#### Article suggestion

Maybe this falls into the purview of a 'site owner' - I think providing guidance on making a good default View in a list or library is pretty important.

I've seen some real trash default Views. And I _think_ bad view design leads to some of the common UX complaints about SharePoint in general.  Conversely, a very good view can really highlight the good user experience that's possible in SharePoint Lists/Libraries

Topics might include:

What's a good view for a highly collaborative list?

What's a good view for a list where people QuickEdit regularly?

How much horizontal scrolling is enough?

Creating views go generate Email notifications.

**Comment by sympmarc** [comment]
This is a great idea! In my experience, most Document Libraries have one view: All documents. And it shows - you guessed it: All documents. 

*Good* views should provide just the right information for people to act or make a good decision. Making views "good" means you have more information about the objects in the list than just the Title and/or file name. Otherwise, you're just using SharePoint ass a network file share, and get very little out of the power of the platform.

An interesting way to frame this would be in a maturity model framework. See: [Capability Maturity Model](https://en.wikipedia.org/wiki/Capability_Maturity_Model). Sadie Van Buren did some excellent work years ago on a [SharePoint Maturity Model](https://www.uwebc.wisc.edu/IT/docs/2011-04-Presentation-SharePointMaturity-Burntsand.pdf). In fact, I'm going to add another issue to bring this thinking into a set of articles!

**Comment by PatD** [comment]
@sympmarc - Please assign to me!

**Comment by sympmarc** [comment]
Done! Looing forward to reading your work...
