### ISSUE TITLE
Power Platform Licensing Article Changes

### ISSUE THREAD

**Issue by sympmarc** [MicrosoftDocs/microsoft-365-community#315]
#### Article issue

After some discussion with my Microsoft counterparts, we'd like to slim down the article to remove the costs and limits and replace those sections with links to the official Power Platform documentation. While one of the goals of this article is to make the licensing more understandable, we won't be able to stay up to date with any changes in the details reliably.

By doing this, we can also shift the focus of the article to better discuss more about why the Power Platform tools are important in Microsoft 365 and what we can do with the tools.

Yes, this does feel a bit like a retreat, but I think it is a reasonable one. @bigpix2000 - let's discuss this here (out in the open) and we can come up with the best way to make the changes.

**Comment by bigpix2000** [comment]
Thank you. I originally want to use links instead of direct displays of tables with the limits and costs but the main source appears to be the PDF and no good way to link to them. Can we ask Microsoft to put that into into linkable doc form then we can definitely work out a more spartan (and focused) version of the article.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sympmarc** [comment]
Great point! Let me look into that.

**Comment by bigpix2000** [comment]
Back to this issue as we will address the bullet item bug #342 along with this change.  Here is what it will look like:

- Updated intro section into what I came up with as the "half page summary" (tested with Ryan Cunninghman 
  {https://twitter.com/rc_says}   Prod Mgr power platform as to validity) then a list of the key licensing levers (capacity related items, specific services, specific bundles), the lookups (although this may be copies of the pdf tables if we truly can't find links) and finally the scenarios (there would be one to three common scenarios at the intro for quicker access leaving the "nuance" ones below.  adding @LuiseFreese to this activity and for her feedback as well on this organization.  thoughts?  let's discuss openly!

**Comment by LuiseFreese** [comment]
few thoughts: Hosted this QnA Licensing session and really got some good insights - working right now on a summarizing blog post with some key-take aways. Would love to point out my maker perspective on Power Platform and why this is not some "nice to have" thingy at the end of M365 adoption road.

**Comment by bigpix2000** [comment]
@LuiseFreese , the perspective you mention is EXACTLY the spirit of the document and also a reason why every effort to "optimize" the information is in order.  On that note, let me repost the "proposed" sections for where the information we have now will find new homes (or be removed because it is superfluous because of a link, etc.) 

- Overview: why this doc, who is it for, how to use this doc
- Core licensing: my "half page" piece which I summarized at the end of the meetup with Ryan but hopefully more artfully written with perhaps three "scenarios" that exemplify the core concepts in action (e.g. app plus flow to o365, flow to premium, AI\RPA with Flow)  
- Licensing Levers: organized by Feature (App, Automate, Virtual Agents) and Lever Type (Trigger, Capacity, AI, RPA, Portal for Apps
- The "lookups" :  This one is a discussion point because here is where @sympmarc suggested links which would be great if they were not hiding in a PDF so some way to optimize without making it obsolete as soon as it is posted needs to be determined.  We might not have a choice and I will have to set a flow to remind me to update it monthly ;-)
- Guidance ( missed this one in my last post) This one is another discussion as it is the key contribution of my experience and John L. and it was supposed to entice practices or additional guidance from the community. For folks making decisions, they would take this section to heart.    
- the Scenarios:  My vision originally was that I would start off with a few scenarios that mix up the pieces above but also entice the community to "submit their scenario" and say what they pay for or had to get (e.g. we got the stand along apps license and we are paying for extra CDS capacity) . This would include a preface section for Automate vs Azure.  Scenarios are not recommendations as much as they are "if you do X, your consequence is Y"  

looking forward to the thoughts!!

**Comment by sympmarc** [comment]
Good to see the discussion here. I'm fairly ignorant about the details of all this, so I leave it in your capable hands!

**Comment by LuiseFreese** [comment]
hi there @bigpix2000 - let's work on that and see how it goes. I would like to write overview and happy to rewrite  the core licensing thing. I think the way I explained it in my blog post here is pretty much that? [my blogpost about PP licensing QnA](https://m365princess.com/power-platform-licensing-qna-key-take-aways/)  -

I agree that PDF are usually a way to hide information..

guidance should be a pretty decent when to use what / most of the time it will be an AND and not an OR. complexity doesnt come with simple answers :-) 

scenarios and examples are a good idea in addition. 

So if you agree I will start with overview and a draft for core licensing... where shall I do that? (Here in the comments? shall I share an md file via OneDrive? Still new to this here.

**Comment by bigpix2000** [comment]
So ..... for authoring, technically you can author in place and we can go back and forth on it like a project but you may also use this space for the content to be reviewed as the same MD tools work here as well.  The overview re-write is a good place to start. As for the core licensing pieces, your blog does cover the discussion and can be used as the model for the "Core" section.  Because of the links issue, I believe we still need to have the additional sections I noted above.  Think of it like this: depending on what the person has come here to see, having the "summary" so they can go away sooner is great so the detail is built up from the overview (to perhaps immediately answer a question) to the Core (the "fast" FAQ in line with your blog) and then "the nitty gritty" where items that took many pages in the PDF files are covered in short and then, at the end the "Scenarios" which I envisioned would grow with community contributions.  

Action item then will be for you to (re) Create the Overview as a draft here in notes. Mention me to follow up and we go back and forth there until its good.  Then same thing with the Core.  After that, depending on if we go Live with Oakdale, I can work on the other sections and you can help review or take up a specific on a section even.   Sound like a plan?  we can have this done before our Chicago M365 Virtual Conference and my session for licensing will highlight our work :)  Danke!! @LuiseFreese

**Comment by LuiseFreese** [comment]
ok, as I wanted to start SOMEWHERE, I did this: 

Please feel free to correct, add, elaborate. 

# Power Platform Licensing

## Overview

This article shall give you a  detailed and easy to understand overview about licensing/pricing regarding Power Platform.

Power Platform consist of Power Apps, Power Automate, Power BI and Power Virtual Agents and has Portals and AI Builder as add-ons.

## Core licensing

We distinguish between Power Apps for Office 365 and Power Apps Standalone

### Power Apps and Power Automate for Office 365

Power Apps and Power Automate for Office 365 means customizing and extending Office with low code. Users can build and run unlimited amount of apps and flows using SharePoint, Excel and dozens of other standard connectors. Now in public preview: Project Oakdale in Teams (“CDS light”). For reference, find a list of all [Power Automate Standard Connectors](https://emea.flow.microsoft.com/en-us/connectors/?filter=&category=standard). 

#### Project Oakdale

Project Oakdale (in public preview) is basically CDS speaking of database and environment but with a more simple security model, but it’s the basic structure of a high scale relational database with tables and the ability to use them in an app.

[About Project Oakdale environment](https://docs.microsoft.com/en-us/power-platform/admin/about-teams-environment)

[Project Oakdale](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq#project-oakdale)

### Power Apps Standalone

#### per user

Power Apps "per user" plan is the equivalent to an "All You Can Eat" Buffet. It means, that users can build and run as many apps using Premium Connectors as they wish.

#### per app

Power Apps "per app" plan is the equivalent to an à la carte menu. It means, that users can build and run a single app.

Any flow that’s working on the same data as the app, doesn’t require an additional license for the flow: We don’t need multiple licenses just to run one use case.

### Licensing Levers

#### organized by Feature

* App
* Automate
* Virtual Agents

#### organized by Lever Type

* Trigger
* Capacity
* AI

    For AI Builder, there is a [gorgeous calculator](https://powerapps.microsoft.com/en-us/ai-builder-calculator/) in which you can calculate the monthly costs.
* RPA
* Portal for Apps

## The "lookups"
This one is a discussion point because here is where @sympmarc suggested links which would be great if they were not hiding in a PDF so some way to optimize without making it obsolete as soon as it is posted needs to be determined. We might not have a choice and I will have to set a flow to remind me to update it monthly ;-)
## Guidance 
( missed this one in my last post) This one is another discussion as it is the key contribution of my experience and John L. and it was supposed to entice practices or additional guidance from the community. For folks making decisions, they would take this section to heart.
## the Scenarios: 

My vision originally was that I would start off with a few scenarios that mix up the pieces above but also entice the community to "submit their scenario" and say what they pay for or had to get (e.g. we got the stand along apps license and we are paying for extra CDS capacity) . This would include a preface section for Automate vs Azure. Scenarios are not recommendations as much as they are "if you do X, your consequence is Y"

**Comment by bigpix2000** [comment]
So @LuiseFreese , now that we are back in the game, the obvious first change will be to Dataverse and away from Oakdale.  Based on the notes so far and the kind of questions and feedback we have seen in just the last couple of months, consider the following organization:

### Overview
summarizing what the doc is about and its purpose and that it does NOT replace the licensing detail, or all those licensing bits posted all over docs
### Core Licensing Concepts
We call out specifically in key bullets or sub headers, the following main concepts:

- Standalone versus "Seeded"  (what they call in in the docs and, yes, we translate this to standalone versus in Office/Dynamics ... I would probably put in here the case of "is it included or will it cost)
- Premium versus Standard (again, the case of if it will cost)
- Capacity (what you get "included" when you have a license and the idea that you can always pay for more)
- The Dataverse exception: the concept of when you are using Teams, some premium items are no longer premium but included .... with the catch
-   Power Apps is based on Apps you run, Power Automate is based on Flows you Create.
 

And then we break this down for additional information:
### Licensing Levers 
(as noted above and the goal here is to unpack the core concepts and yes, include the link to the AI calculator) 
### Guidance 
(There will be some major bullets I see here as dataverse totally changed much of what was put up before!)
Here are some bullet highlights (just examples but perhaps maybe ...?)
- Do your App\Flow in Teams wherever possible
- Dataverse over Other Data "premium connections", and free version over SP Lists for functionality
- know your data to pick the right sized data repo and the repo that will cost the lease when you push it through to Power BI
- Take advantage of any free thing wherever possible (reminder of the community environment!) 
- Think Governance early not after (control costs, set up "samples" for others to follow etc) corollary:  Adopt best practices or implement the COE
- The license docs are updated often (lately its been monthly) Take time to review changes as often as you can to catch those not heavily publicized.  
- Think of your scale and what that is worth to you or your organization.  

### Scenarios
initially at least one to exemplify the core concepts and then a call to action for contributions. 
### Links
The (hopefully not to be changed) direct links to the sources such as the main PDF and the starting points for the various license details  

Once we are final on the organization, I will make the change in a workspace and we can share that for editing .... we will advise @sympmarc when we agree we are "done" :-)

**Comment by LuiseFreese** [comment]
hi there, I struggled with commenting here and scrolling up and down so I put my takes into my blog repo, its public and you will find it here: 

[Power Platform Licensing](https://github.com/LuiseFreese/blog/blob/main/fordocs/Power-Platform-Licensing.md)

Let me know what you think @bigpix2000

**Comment by bigpix2000** [comment]
Got busy and will be deep diving the link above .... interestingly I got pinged by the community on License questions that actually gave some validation for the pieces we are working on as well as a note for one additional (or modified) sample that is current.

**Comment by bigpix2000** [comment]
Got busy and will be deep diving the link above .... interestingly I got pinged by the community on License questions that actually gave some validation for the pieces we are working on as well as a note for one additional (or modified) sample that is current.

**Comment by bigpix2000** [comment]
Got busy and will be deep diving the link above .... interestingly I got pinged by the community on License questions that actually gave some validation for the pieces we are working on as well as a note for one additional (or modified) sample that is current.
