### ISSUE TITLE
Seeded Power Automate licensing Question

### ISSUE THREAD

**Issue by ismaen** [MicrosoftDocs/microsoft-365-community#364]
Hello, 

Under the Power Automate > Seeded Power Automate section, there is a line item that states "Standard and Premium connectors included only when in context of Office 365 or Dynamics." I had a customer ask me about this, and to my knowledge this isn't necessarily true. Premium connectors ultimately require a per flow/per user plan and regardless of the context it is in, are not included. Can I get some clarification on this?
![msfdocs](https://user-images.githubusercontent.com/5711276/98284315-c56f0280-1f55-11eb-9614-192fdfdeab50.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c843089f-7829-b8b4-3fcd-ef52bdc4f764
* Version Independent ID: a44c5d15-81cc-9d34-dd2e-8361f0852034
* Content: [Understanding Power Platform Licensing](https://docs.microsoft.com/en-us/microsoft-365/community/powerplatformlicensingforcitizendeveloper#power-automate)
* Content Source: [Community/powerplatformlicensingforcitizendeveloper.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/live/Community/powerplatformlicensingforcitizendeveloper.md)
* Service: **power-platform**
* GitHub Login: @bigpix2000
* Microsoft Alias: **jhendr**

**Comment by sympmarc** [comment]
@bigpix2000 - Can you answer this one?

**Comment by bigpix2000** [comment]
@sympmarc  - yes I can.  @ismaen:  This one piece tripped me up early when I created the first draft of this document and the core concept is if you are using a connector to something specifically talking to something in Office 365 (SharePoint) or something in Dynamics, you should not have to pay extra for it because the Office or Dynamics license includes it. What does trip us up is mixing in CDS access where we know that CDS is a premium service and NOT inlcuded with the Office Seeded license and, depending on how it is set up, potentially NOT part of the particular Dynamics license the user has.  The system will "get mad" and demand a license on what seemingly is a connection to what feels like should be included.  Unfortunately THAT aspect is nuanced and hard to cover as a summary.  But as we are ready to update this document with knowledge such as this, the rule of thumb is as follows: Seeded licenses means Apps or Flow "connecting" to apps included with the seat license (Office or Dynamics) but NOT to Storage options (CDS) which is always Premium with few exceptions (Project Oakley being the latest and some Enterprise level Dynamics apps including CDS in the same manner) .  If you have a specific scenario that defies this, please post the specifics of the app or flow and we can confirm it ( and perhaps add it to the "samples")  Thank you!

**Comment by ismaen** [comment]
@bigpix2000 thank you for the response, this was really helpful!

**Comment by bigpix2000** [comment]
@ismaen and @sympmarc Glas I was able to help .... Community prevails again :-)
