### ISSUE TITLE
Using the internal name of a SharePoint column does not work in some instances

### ISSUE THREAD

**Issue by karimegitHub** [MicrosoftDocs/microsoft-365-community#552]
Using the internal name of a SharePoint column does not work in some instances.

Example, easily reproducible:
SharePoint column name JV2
Internal name _x400a_V2

Using the internal name  _x400a_V2 in a Power Automate filter query results in "Column ‘_x004a_V2’ does not exist".

Using Power Automate peek code or hovering over the Power Automate dynamic content for field JV2 reveals that the internal name to use is actually:  OData_x004a_v2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4820cfd-6c16-cf3d-dafe-faebe9db24ca
* Version Independent ID: 041df04f-8b58-d8a3-82a0-bfb330a7c3c9
* Content: [SharePoint Naming Guidelines](https://docs.microsoft.com/en-us/microsoft-365/community/sharepoint-naming-guidelines?source=docs#internal-names)
* Content Source: [Community/sharepoint-naming-guidelines.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/sharepoint-naming-guidelines.md)
* Service: **sharepoint-online**
* GitHub Login: @pkbullock
* Microsoft Alias: **daisyfeller**

**Comment by CallumCrowley** [comment]
@karimegitHub The use of internal names is generally recommended when referencing columns. This is because internal names are immutable, while the display name could be changed by a user at any time meaning any customisation depending on that column could break if you are referencing it using a display name. Even if Power Automate does have a different way of looking up SharePoint columns, this would not change this advice as it is recommended in most scenarios e.g. when referencing SharePoint columns in PowerShell.
