### ISSUE TITLE
If you can Enable versioning, you can Disable versioning. 

### ISSUE THREAD

**Issue by jadesolis** [MicrosoftDocs/microsoft-365-community#664]
#https://docs.microsoft.com/en-us/microsoft-365/community/versioning-basics-best-practices

Article state "If you can Enable versioning, you can Disable versioning. "
So if versioning is enabled by default (no other option to 'enable' it) does it mean we can't turn it off? the Statement semantics is ambiguous..
Can we have supporting links on how to actually turn off versioning?

**Comment by sympmarc** [comment]
Sorry for the delay in getting to this, @jadesolis. The answer varies based on what version of SharePoint you're working with. If you're on SharePoint Online, you *can* disable versioning - at least I was just able to do so in a test tenant. @PatD, as the original author of this, have you seen otherwise?

**Comment by tseward** [comment]
All versions of SharePoint Server support disabling versioning, so it shouldn't matter what version of SharePoint is in-use.
