### ISSUE TITLE
Page out of date

### ISSUE THREAD

**Issue by ResRudeBoy** [MicrosoftDocs/microsoft-365-community#815]
Page is now incorrect. connector has attachement name and content fields now.
![image](https://user-images.githubusercontent.com/43776608/234489539-f226162a-719b-439f-997a-b278bb5b96a6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: efceafa2-4c75-9534-5826-8d6f13391c8b
* Version Independent ID: 41bbd300-95aa-6eac-fa8a-dbc735c94102
* Content: [Power Automate - Send SharePoint files as attachments](https://learn.microsoft.com/en-us/microsoft-365/community/power-automate-send-sharepoint-files-as-attachments)
* Content Source: [Community/power-automate-send-sharepoint-files-as-attachments.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/power-automate-send-sharepoint-files-as-attachments.md)
* Service: **power-platform**
* GitHub Login: @JimmyHang
* Microsoft Alias: **daisyfeller**

**Comment by sympmarc** [comment]
@JimmyHang Is this something you'd like to look at?

**Comment by sympmarc** [comment]
@ResRudeBoy - Our apologies for not responding sooner. Thanks very much for the issue.

I just took a look at the **Send an email (v2)** action, and there are still two modes, depending on how you'd like to provide the attachment info. 

Default:
![image](https://github.com/MicrosoftDocs/microsoft-365-community/assets/1295627/ea29f2a1-ddd1-4b53-8196-98d2611ff51a)

Array input:
![image](https://github.com/MicrosoftDocs/microsoft-365-community/assets/1295627/ce8aa991-3f00-45df-a575-1e3b2ff015c0)

In this article, @JimmyHang has chosen to use the latter option because he wants to send an array of attachments he's built in prior actions.

I'm going to close this issue, but please let us know if you think I'm missing something by opening a new issue.
